name: Publish App

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  AZURE_WEB_APP: tickettoolkit
  AZURE_WEB_APP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Step 3: Restore dependencies
      - name: Restore
        run: dotnet restore ./TicketToolkit.sln

      # Step 4: Build the solution
      - name: Build
        run: dotnet build ./TicketToolkit.sln --configuration Release --no-restore

      # Step 5: Publish the main project (not the test project)
      - name: Publish
        run: dotnet publish ./TicketToolkit/TicketToolkit.csproj --configuration Release --framework net8.0 --output ${{ env.AZURE_WEB_APP_PACKAGE_PATH }} --no-restore

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEB_APP }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEB_APP_PACKAGE_PATH }}
