name: Publish App

on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore ./tickettoolkit.sln

      - name: Build
        run: dotnet build ./tickettoolkit.sln --no-restore
      - name: Publish
        run: dotnet publish ./tickettoolkit.sln --no-build
      
